#pragma once
// ─────────────────────────────────────────────────────────────────────────────
// SPLAY transport polynomial coefficients
//
// Generated by tools/generate_transport_fits.py using Cantera data.
// Gas     : argon, nitrogen
// Fit form: mu(T) = sum_{k=0..4} mu_k * T^k   [Pa·s]
//           k(T)  = sum_{k=0..4}  k_k * T^k   [W/(m·K)]
// T range  : 200 K – 5000 K
// Samples  : 400
// Date     : 2026-06-06 (placeholder; regenerate with the Python tool)
//
// IMPORTANT: These are pre-generated placeholder coefficients derived from
// known power-law fits for argon and nitrogen.  Re-run the Python utility to
// obtain Cantera-accurate coefficients for your T range.
// ─────────────────────────────────────────────────────────────────────────────

namespace splay {
namespace transport_data {

// ── Argon ────────────────────────────────────────────────────────────────────
// Sutherland-class polynomial fit, valid 200–5000 K.
// mu(T) ~ 2.228e-5 * (T/300)^0.72   ; fitted as a 4th-order poly below.
// k (T) ~ 1.771e-2 * (T/300)^0.72

constexpr double argon_T_min =  200.0;
constexpr double argon_T_max = 5000.0;

// Viscosity coefficients  (Pa·s)
constexpr double argon_mu[5] = {
     2.3566e-06,   // a0
     7.2985e-08,   // a1
    -1.1049e-11,   // a2
     1.1027e-15,   // a3
    -4.0440e-20    // a4
};

// Conductivity coefficients  (W/(m·K))
constexpr double argon_k[5] = {
     1.8768e-03,   // b0
     5.8041e-05,   // b1
    -8.7878e-09,   // b2
     8.7705e-13,   // b3
    -3.2157e-17    // b4
};

// ── Nitrogen ─────────────────────────────────────────────────────────────────
// mu(T) ~ 1.663e-5 * (T/300)^0.67   ; fitted as 4th-order poly.
// k (T) ~ 2.495e-2 * (T/300)^0.67   (diatomic, higher k than Ar)

constexpr double nitrogen_T_min =  200.0;
constexpr double nitrogen_T_max = 5000.0;

// Viscosity coefficients  (Pa·s)
constexpr double nitrogen_mu[5] = {
     4.0088e-06,   // a0
     6.3541e-08,   // a1
    -8.6154e-12,   // a2
     7.6861e-16,   // a3
    -2.5990e-20    // a4
};

// Conductivity coefficients  (W/(m·K))
constexpr double nitrogen_k[5] = {
     6.0193e-03,   // b0
     9.5247e-05,   // b1
    -1.2916e-08,   // b2
     1.1519e-12,   // b3
    -3.8980e-17    // b4
};

} // namespace transport_data
} // namespace splay
