#!/usr/bin/env python3
"""
SPLAY transport coefficient generator.

Uses Cantera to sample viscosity and thermal conductivity for pure argon and
pure nitrogen, then fits 4th-order polynomials and writes a C++ header.

Usage
-----
    python tools/generate_transport_fits.py \
        --gas argon \
        --tmin 200 \
        --tmax 5000 \
        --samples 400 \
        --output include/splay/transport_coeffs.hpp

Requirements
------------
    pip install cantera numpy scipy

If Cantera is not available, the script falls back to Sutherland-law
analytic values and prints a warning.
"""

import argparse
import sys
import datetime
import numpy as np

# ---------------------------------------------------------------------------
# Cantera interface (optional)
# ---------------------------------------------------------------------------
try:
    import cantera as ct
    HAS_CANTERA = True
except ImportError:
    HAS_CANTERA = False


def sample_cantera(gas_name: str, T_array: np.ndarray):
    """Return (mu, k) arrays via Cantera at fixed P=1 atm."""
    if gas_name == "argon":
        species = "AR"
        mechanism = "air.yaml"
    elif gas_name == "nitrogen":
        species = "N2"
        mechanism = "air.yaml"
    else:
        raise ValueError(f"Unsupported gas: {gas_name}")

    gas = ct.Solution(mechanism)
    mu_arr = np.zeros_like(T_array)
    k_arr  = np.zeros_like(T_array)
    for i, T in enumerate(T_array):
        gas.TPX = T, ct.one_atm, {species: 1.0}
        mu_arr[i] = gas.viscosity
        k_arr[i]  = gas.thermal_conductivity
    return mu_arr, k_arr


# ---------------------------------------------------------------------------
# Sutherland-law fallback
# ---------------------------------------------------------------------------
SUTHERLAND = {
    "argon": {
        "mu_ref": 2.228e-5,   # Pa·s at T_ref
        "T_ref":  300.0,
        "S":      144.4,       # Sutherland constant (K)
        "k_ref":  1.771e-2,   # W/(m·K) at T_ref
        "Pr":     0.667,
    },
    "nitrogen": {
        "mu_ref": 1.663e-5,
        "T_ref":  300.0,
        "S":      106.7,
        "k_ref":  2.495e-2,
        "Pr":     0.713,
    },
}


def sample_sutherland(gas_name: str, T_array: np.ndarray):
    p = SUTHERLAND[gas_name]
    mu_ref = p["mu_ref"]
    T_ref  = p["T_ref"]
    S      = p["S"]
    k_ref  = p["k_ref"]
    Pr     = p["Pr"]

    mu_arr = mu_ref * (T_array / T_ref) ** 1.5 * (T_ref + S) / (T_array + S)
    # k ~ mu * cp / Pr  but for monoatomic/diatomic ideal gas we scale k directly
    k_arr  = k_ref  * (T_array / T_ref) ** 1.5 * (T_ref + S) / (T_array + S)
    return mu_arr, k_arr


# ---------------------------------------------------------------------------
# Polynomial fitting
# ---------------------------------------------------------------------------
def fit_poly4(T: np.ndarray, y: np.ndarray):
    """Fit y = a0 + a1*T + a2*T^2 + a3*T^3 + a4*T^4."""
    coeffs = np.polyfit(T, y, 4)
    # np.polyfit returns [a4, a3, a2, a1, a0]  (highest degree first)
    return coeffs[::-1]   # return [a0, a1, a2, a3, a4]


# ---------------------------------------------------------------------------
# Header writer
# ---------------------------------------------------------------------------
HEADER_TEMPLATE = '''\
#pragma once
// ─────────────────────────────────────────────────────────────────────────────
// SPLAY transport polynomial coefficients
//
// Generated by tools/generate_transport_fits.py
// Date    : {date}
// Source  : {source}
// Fit form: mu(T) = sum_{{k=0..4}} mu_k * T^k   [Pa·s]
//           k(T)  = sum_{{k=0..4}}  k_k * T^k   [W/(m·K)]
// ─────────────────────────────────────────────────────────────────────────────

namespace splay {{
namespace transport_data {{

// ── Argon ────────────────────────────────────────────────────────────────────
// Samples: {argon_samples}   T range: {argon_Tmin} K – {argon_Tmax} K

constexpr double argon_T_min = {argon_Tmin};
constexpr double argon_T_max = {argon_Tmax};

// Viscosity coefficients  (Pa·s)
constexpr double argon_mu[5] = {{
    {argon_mu0},   // a0
    {argon_mu1},   // a1
    {argon_mu2},   // a2
    {argon_mu3},   // a3
    {argon_mu4}    // a4
}};

// Conductivity coefficients  (W/(m·K))
constexpr double argon_k[5] = {{
    {argon_k0},   // b0
    {argon_k1},   // b1
    {argon_k2},   // b2
    {argon_k3},   // b3
    {argon_k4}    // b4
}};

// ── Nitrogen ─────────────────────────────────────────────────────────────────
// Samples: {nitrogen_samples}   T range: {nitrogen_Tmin} K – {nitrogen_Tmax} K

constexpr double nitrogen_T_min = {nitrogen_Tmin};
constexpr double nitrogen_T_max = {nitrogen_Tmax};

// Viscosity coefficients  (Pa·s)
constexpr double nitrogen_mu[5] = {{
    {nitrogen_mu0},   // a0
    {nitrogen_mu1},   // a1
    {nitrogen_mu2},   // a2
    {nitrogen_mu3},   // a3
    {nitrogen_mu4}    // a4
}};

// Conductivity coefficients  (W/(m·K))
constexpr double nitrogen_k[5] = {{
    {nitrogen_k0},   // b0
    {nitrogen_k1},   // b1
    {nitrogen_k2},   // b2
    {nitrogen_k3},   // b3
    {nitrogen_k4}    // b4
}};

}} // namespace transport_data
}} // namespace splay
'''


def format_coeff(v):
    return f"{v:.10e}"


def generate_gas(gas_name, T_array, use_cantera):
    if use_cantera and HAS_CANTERA:
        print(f"  [{gas_name}] Using Cantera ...", end=" ", flush=True)
        mu, k = sample_cantera(gas_name, T_array)
        source = "Cantera"
    else:
        if not HAS_CANTERA:
            print(f"  [{gas_name}] Cantera not found; using Sutherland law.")
        else:
            print(f"  [{gas_name}] Using Sutherland law (--no-cantera).")
        mu, k = sample_sutherland(gas_name, T_array)
        source = "Sutherland law"

    mu_c = fit_poly4(T_array, mu)
    k_c  = fit_poly4(T_array, k)

    # Sanity check: no negative values in fit range
    T_check = T_array
    mu_check = np.polyval(mu_c[::-1], T_check)
    k_check  = np.polyval(k_c[::-1],  T_check)
    if np.any(mu_check <= 0):
        print(f"  WARNING: mu polynomial has non-positive values in fit range for {gas_name}!")
    if np.any(k_check <= 0):
        print(f"  WARNING: k polynomial has non-positive values in fit range for {gas_name}!")

    print(f"done  (mu_max={mu.max():.4e}, k_max={k.max():.4e})")
    return mu_c, k_c, source


def main():
    parser = argparse.ArgumentParser(description="Generate SPLAY transport coefficient header.")
    parser.add_argument("--gas",     choices=["argon", "nitrogen", "both"], default="both")
    parser.add_argument("--tmin",    type=float, default=200.0,  help="Min temperature (K)")
    parser.add_argument("--tmax",    type=float, default=5000.0, help="Max temperature (K)")
    parser.add_argument("--samples", type=int,   default=400,    help="Number of sample points")
    parser.add_argument("--output",  type=str,   default="include/splay/transport_coeffs.hpp")
    parser.add_argument("--no-cantera", action="store_true", help="Force Sutherland fallback")
    args = parser.parse_args()

    use_cantera = not args.no_cantera

    print(f"SPLAY transport fit generator")
    print(f"  T range : {args.tmin} – {args.tmax} K")
    print(f"  Samples : {args.samples}")
    print(f"  Output  : {args.output}")
    print()

    T_array = np.linspace(args.tmin, args.tmax, args.samples)

    source = "Sutherland law"

    ar_mu_c, ar_k_c, src_ar   = generate_gas("argon",    T_array, use_cantera)
    n2_mu_c, n2_k_c, src_n2   = generate_gas("nitrogen", T_array, use_cantera)
    source = src_ar  # both use same source

    header = HEADER_TEMPLATE.format(
        date=datetime.date.today().isoformat(),
        source=source,
        argon_samples=args.samples,
        argon_Tmin=args.tmin,
        argon_Tmax=args.tmax,
        argon_mu0=format_coeff(ar_mu_c[0]),
        argon_mu1=format_coeff(ar_mu_c[1]),
        argon_mu2=format_coeff(ar_mu_c[2]),
        argon_mu3=format_coeff(ar_mu_c[3]),
        argon_mu4=format_coeff(ar_mu_c[4]),
        argon_k0=format_coeff(ar_k_c[0]),
        argon_k1=format_coeff(ar_k_c[1]),
        argon_k2=format_coeff(ar_k_c[2]),
        argon_k3=format_coeff(ar_k_c[3]),
        argon_k4=format_coeff(ar_k_c[4]),
        nitrogen_samples=args.samples,
        nitrogen_Tmin=args.tmin,
        nitrogen_Tmax=args.tmax,
        nitrogen_mu0=format_coeff(n2_mu_c[0]),
        nitrogen_mu1=format_coeff(n2_mu_c[1]),
        nitrogen_mu2=format_coeff(n2_mu_c[2]),
        nitrogen_mu3=format_coeff(n2_mu_c[3]),
        nitrogen_mu4=format_coeff(n2_mu_c[4]),
        nitrogen_k0=format_coeff(n2_k_c[0]),
        nitrogen_k1=format_coeff(n2_k_c[1]),
        nitrogen_k2=format_coeff(n2_k_c[2]),
        nitrogen_k3=format_coeff(n2_k_c[3]),
        nitrogen_k4=format_coeff(n2_k_c[4]),
    )

    with open(args.output, "w") as f:
        f.write(header)

    print(f"\nWrote {args.output}")


if __name__ == "__main__":
    main()
